module.exports = {
    events: [
      {
        id: 1,
        name: "Event 001 - Partner1",
        organization: "Partner1",
        date: "2021-10-10T10:00:00",
        price: 100,
        rating: "L14",
        image_url: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
        created_at: "2023-09-09T00:10:10",
        location: "São Paulo, SP",
      },
      {
        id: 2,
        name: "Event 002 - Partner1",
        organization: "Partner1",
        date: "2021-10-10T12:00:00",
        price: 200,
        rating: "L14",
        image_url: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea",
        created_at: "2023-09-09T00:10:10",
        location: "Rio de Janeiro, RJ",
      },
      {
        id: 3,
        name: "Event 003 - Partner2",
        organization: "Partner2",
        date: "2024-10-10T10:00:00",
        price: 400,
        rating: "L12",
        image_url: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14",
        created_at: "2023-09-09T00:10:10",
        location: "Belo Horizonte, MG",
      },
      {
        id: 4,
        name: "Event 004 - Partner2",
        organization: "Partner2",
        date: "2023-09-11T00:00:00",
        price: 500,
        rating: "L16",
        image_url: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f",
        created_at: "2023-09-09T00:10:10",
        location: "Uberlândia, MG",
      },
    ],
    spots: [
        {id: 1, name: "A1", status: 'available', event_id: 1},
        {id: 2, name: "A2", status: 'available', event_id: 1},
        {id: 3, name: "A3", status: 'available', event_id: 1},
        {id: 4, name: "A4", status: 'available', event_id: 1},
        {id: 5, name: "A5", status: 'available', event_id: 1},
        {id: 6, name: "B1", status: 'available', event_id: 1},
        {id: 7, name: "B2", status: 'available', event_id: 1},
        {id: 8, name: "B3", status: 'available', event_id: 1},
        {id: 9, name: "B4", status: 'available', event_id: 1},
        {id: 10, name: "B5", status: 'available', event_id: 1},

        {id: 1, name: "A1", status: 'available', event_id: 2},
        {id: 2, name: "A2", status: 'available', event_id: 2},
        {id: 3, name: "A3", status: 'available', event_id: 2},
        {id: 4, name: "A4", status: 'available', event_id: 2},
        {id: 5, name: "A5", status: 'available', event_id: 2},
        {id: 6, name: "A6", status: 'available', event_id: 2},
        {id: 7, name: "A7", status: 'available', event_id: 2},
        {id: 8, name: "A8", status: 'available', event_id: 2},
        {id: 9, name: "A9", status: 'available', event_id: 2},
        {id: 10, name: "A10", status: 'available', event_id: 2},
        {id: 11, name: "B1", status: 'available', event_id: 2},
        {id: 12, name: "B2", status: 'available', event_id: 2},
        {id: 13, name: "B3", status: 'available', event_id: 2},
        {id: 14, name: "B4", status: 'available', event_id: 2},
        {id: 15, name: "B5", status: 'available', event_id: 2},
        {id: 16, name: "B6", status: 'available', event_id: 2},
        {id: 17, name: "B7", status: 'available', event_id: 2},
        {id: 18, name: "B8", status: 'available', event_id: 2},
        {id: 19, name: "B9", status: 'available', event_id: 2},
        {id: 20, name: "B10", status: 'available', event_id: 2},

        {id: 1, name: "A1", status: 'available', event_id: 3},
        {id: 2, name: "A2", status: 'available', event_id: 3},
        {id: 3, name: "A3", status: 'available', event_id: 3},
        {id: 4, name: "A4", status: 'available', event_id: 3},
        {id: 5, name: "A5", status: 'available', event_id: 3},
        {id: 6, name: "A6", status: 'available', event_id: 3},
        {id: 7, name: "A7", status: 'available', event_id: 3},
        {id: 8, name: "A8", status: 'available', event_id: 3},
        {id: 9, name: "A9", status: 'available', event_id: 3},
        {id: 10, name: "A10", status: 'available', event_id: 3},
        {id: 11, name: "A11", status: 'available', event_id: 3},
        {id: 12, name: "A12", status: 'available', event_id: 3},
        {id: 13, name: "A13", status: 'available', event_id: 3},
        {id: 14, name: "A14", status: 'available', event_id: 3},
        {id: 15, name: "A15", status: 'available', event_id: 3},
        {id: 16, name: "B1", status: 'available', event_id: 3},
        {id: 17, name: "B2", status: 'available', event_id: 3},
        {id: 18, name: "B3", status: 'available', event_id: 3},
        {id: 19, name: "B4", status: 'available', event_id: 3},
        {id: 20, name: "B5", status: 'available', event_id: 3},
        {id: 21, name: "B6", status: 'available', event_id: 3},
        {id: 22, name: "B7", status: 'available', event_id: 3},
        {id: 23, name: "B8", status: 'available', event_id: 3},
        {id: 24, name: "B9", status: 'available', event_id: 3},
        {id: 25, name: "B10", status: 'available', event_id: 3},
        {id: 26, name: "B11", status: 'available', event_id: 3},
        {id: 27, name: "B12", status: 'available', event_id: 3},
        {id: 28, name: "B13", status: 'available', event_id: 3},
        {id: 29, name: "B14", status: 'available', event_id: 3},
        {id: 30, name: "B15", status: 'available', event_id: 3},
    ]
  };
  